### ISSUE TITLE
AD sync not syncing all group members

### ISSUE THREAD

**Issue by jeremyp** [dssit/roles-management#108]
Just checked on the AD sync between RM and the dss-us-cmb-rivera-[users|admin] groups in AD. For both of them, only a subset of the members in the AD group are appearing in RM. Based on a quick glance, it does look like the people NOT being synced are the ones in the ucdStudents OU in uConnect AD (though students who are already in RM are being synced correctly).

**Comment by cthielen** [comment]
Closing due to age. It should be re-opened if still needed.
