### ISSUE TITLE
impersonate doesn't work consistently

### ISSUE THREAD

**Issue by jeremyp** [dssit/roles-management#154]
Two different things I noticed:

1. I wasn't able to impersonate user crcasell (it shows Not Found, even though she's definitely in the system).

2. After using the application for a few minutes, then going back to the Impersonate dialog, the Found/Not Found no longer appears when entering a login ID. Doing a force-reload resolved this.

**Comment by cthielen** [comment]
Closing due to age. It should be re-reported if this still occurs.
