### ISSUE TITLE
with many application cards, it requires scrolling to edit users/groups for an application role

### ISSUE THREAD

**Issue by jeremyp** [dssit/roles-management#156]
For users with many applications, an application card may appear at the bottom of a very long list. After selecting an application role, the user must scroll back to the top of the page to see or edit the users and groups assigned to that role. It's somewhat confusing. 

Possible suggestions: 

1. when you search for a particular application, have the other application cards not matching the search criteria disappear. 

2. Have the user/group list scroll independently of the application card pane, so that even when looking at an application card at the bottom of the list, the user/group pane "stays put."

**Comment by cthielen** [comment]
Closing due to age. It should be re-opened if still needed. This will be addressed in the v2 UI update.
