### ISSUE TITLE
user sometimes appears in list, sometimes doesn't

### ISSUE THREAD

**Issue by jmcarlso** [dssit/roles-management#164]
Michelle Richter Smith in Goodman Lab Admin group - doesn't appear when pulling up list, then a few minutes later when pulling up the list again she does appear (I have screen shots from 4:27 pm and 4:29 pm - maybe you were making changes?).  The roles listed in her details is "Lab User" and "Lab Admin" this afternoon, but i removed her from "Lab User" and added her to "Lab Admin" this morning.  She doesn't appear in "Lab User" (which is correct).  I did try adding/removing in Lab User to see if the role in her details would go away (did not) and added her again in Lab Admins again but she's doesn't appear to be showing up in the "Lab Admins" group.  Her AD3 account is not disabled.  Basically right now, sometimes Lab Admins shows up with 38, sometimes with 43 (the difference being those 4 users I mentioned earlier that you said were disabled in RM and Michelle)

**Comment by cthielen** [comment]
Closing due to age and the significance of caching changes which may have affected this issue. It should be re-reported and details gathered should it happen again.
